# Generated by Django 3.1.7 on 2021-03-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done'), ('procrastinated', 'Procrastinated'), ('canceled', 'Canceled')], default='new', max_length=25),
        ),
    ]
