# Generated by Django 3.1.7 on 2021-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(choices=[(1, 'Trivial'), (2, 'Minor'), (3, 'Major'), (4, 'Critical'), (5, 'Blocker')], default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('procrastinated', 'Procrastinated'), ('canceled', 'Canceled'), ('done', 'Done')], default='new', max_length=25),
        ),
    ]
